name: 🚀 Deploy Dev to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_DEV_SSH_KEY }}

      - name: Deploy to Dev EC2
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ubuntu@${{ secrets.EC2_DEV_HOST }} << 'EOF'
            # Navigate to your existing app folder
            cd ~/mineapp

            # Reset local changes (optional) and pull latest dev code
            git reset --hard
            git clean -fd
            git checkout dev
            git pull origin dev

            # Backend setup
            cd backend
            npm install
            pm2 restart backend || pm2 start index.js --name backend

            # Frontend setup
            cd ../frontend
            npm install
            pm2 restart frontend || pm2 start npm --name frontend -- start
          EOF
